kind: Pod
apiVersion: v1
metadata:
  name: shipping-app
  labels:
    app: shipping
spec:
  containers:
    - name: shipping-app
      image: hashicorp/http-echo
      args:
        - "-text=shipping"

---

kind: Service
apiVersion: v1
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping
  ports:
    - port: 5678 # Default port for image
