kind: Pod
apiVersion: v1
metadata:
  name: customers-app
  labels:
    app: customers
spec:
  containers:
    - name: customers-app
      image: gnm3000/customers_microservice:latest
      imagePullPolicy: Always
      env:
      - name: MONGODB_URL
        value: mongodb://adminuser:password123@mongo-nodeport-svc.default.svc.cluster.local/?retryWrites=true&w=majority
      - name: RABBITMQ_USER
        value: guest
      - name: RABBITMQ_PASS
        value: guest
      - name: RABBITMQ_SERVER
        value: production-rabbitmqcluster.default.svc.cluster.local
      - name: RABBITMQ_PORT
        value: '5672'
      - name: BASEURL_SALES_SERVICE
        value: http://sales-service.default.svc.cluster.local:5678 
      
      
      
---

kind: Service
apiVersion: v1
metadata:
  name: customers-service
spec:
  selector:
    app: customers
  ports:
    - port: 5678 # Default port for image
