docker push gnm3000/shipping_microservice_worker:latest
docker push gnm3000/sales_microservice_worker:latest
docker push gnm3000/customers_microservice_worker:latest
docker push gnm3000/reporting_microservice:latest
docker push gnm3000/shipping_microservice:latest
docker push gnm3000/sales_microservice:latest
docker push gnm3000/customers_microservice:latest